### ISSUE TITLE
Update documentation for list methods

### ISSUE THREAD

**Issue by Harmon758** [tweepy/tweepy#1210]
Documentation for list methods has been out of date since https://github.com/tweepy/tweepy/commit/5be123101fc5f8959bb5bed64095ce45f8828b38, https://github.com/tweepy/tweepy/commit/b144a8e617525f7a6896b68270fcf5bb437e02a9, and https://github.com/tweepy/tweepy/commit/a5f75d89a820242e439d315b86a2c2d849505b9f as part of Tweepy 2.0. The documentation for the following methods need to be updated:
- [X] [`API.destroy_list`](https://tweepy.readthedocs.io/en/latest/api.html#API.destroy_list): https://github.com/tweepy/tweepy/commit/ba3f473cfb7729f21f11b54d31fa7586672b02ca
- [X] [`API.update_list`](https://tweepy.readthedocs.io/en/latest/api.html#API.update_list): https://github.com/tweepy/tweepy/commit/e7ff4abf67d58d8f186be22eef4f7f0d162dc4cf
- [X] [`API.lists_all`](https://tweepy.readthedocs.io/en/latest/api.html#API.lists_all): https://github.com/tweepy/tweepy/commit/5a3196f602b61e7b4ea4424c2bac0aa5200b9a8c
- [X] [`API.lists_memberships`](https://tweepy.readthedocs.io/en/latest/api.html#API.lists_memberships): https://github.com/tweepy/tweepy/commit/d630f8e4a69b969532056caf382dbb3010f453e1
- [X] [`API.lists_subscriptions`](https://tweepy.readthedocs.io/en/latest/api.html#API.lists_subscriptions): https://github.com/tweepy/tweepy/commit/9e89ead93f6cf72444646cf1b19673859d00bd4c
- [X] [`API.list_timeline`](https://tweepy.readthedocs.io/en/latest/api.html#API.list_timeline): https://github.com/tweepy/tweepy/commit/c7bede164197887489b5f1fa53dae5aad04dbc0b
- [X] [`API.get_list`](https://tweepy.readthedocs.io/en/latest/api.html#API.get_list) (#1201): https://github.com/tweepy/tweepy/commit/e1181a69c7d20c1dbda7a1d58ee14a1e6309ca21
- [X] [`API.add_list_member`](https://tweepy.readthedocs.io/en/latest/api.html#API.add_list_member) (#704): https://github.com/tweepy/tweepy/commit/5b421cf56a5f7feec4bb63f8d60e0ab9be7f90ad, https://github.com/tweepy/tweepy/commit/68f7f702ba2a5ce4ca14dbfe8f8cae4f05b914fa
- [X] [`API.remove_list_member`](https://tweepy.readthedocs.io/en/latest/api.html#API.remove_list_member): https://github.com/tweepy/tweepy/commit/b1e88b2a21c32746b04cfbf5b70dfe9dc89c5306
- [X] [`API.list_members`](https://tweepy.readthedocs.io/en/latest/api.html#API.list_members) (#738): https://github.com/tweepy/tweepy/commit/daa4456cd44a25d0ad273e4006863274d81cb0c2
- [X] `API.is_list_member` -> [`API.show_list_member`](https://tweepy.readthedocs.io/en/latest/api.html#API.show_list_member) (#697): https://github.com/tweepy/tweepy/commit/685612f5d3c0d1ee913266c853743086a9c550df
- [X] [`API.subscribe_list`](https://tweepy.readthedocs.io/en/latest/api.html#API.subscribe_list): https://github.com/tweepy/tweepy/commit/846fed9b05cc1b380feb5607beedbc37af67df7f
- [X] [`API.unsubscribe_list`](https://tweepy.readthedocs.io/en/latest/api.html#API.unsubscribe_list): https://github.com/tweepy/tweepy/commit/24206f23f4652505cdb3f55eab47f954002d982a
- [X] [`API.list_subscribers`](https://tweepy.readthedocs.io/en/latest/api.html#API.list_subscribers): https://github.com/tweepy/tweepy/commit/83899bf64a701fe0e932e3ced49be8cf61caf0f2
- [X] `API.is_subscribed_list` -> [`API.show_list_subscriber`](https://tweepy.readthedocs.io/en/latest/api.html#API.show_list_subscriber) (#1202): https://github.com/tweepy/tweepy/commit/1eeaaf71ec7b6ae90ef7cfda24836bded939f733

Additionally, two new list methods were added with https://github.com/tweepy/tweepy/commit/0c0c696c24788f4d412fc73d5a6b680484633da2 as part of Tweepy v3.0.0.
These methods need to be documented:
- [X] [`API.add_list_members`](https://tweepy.readthedocs.io/en/latest/api.html#API.add_list_members) (#704): https://github.com/tweepy/tweepy/commit/5b421cf56a5f7feec4bb63f8d60e0ab9be7f90ad, https://github.com/tweepy/tweepy/commit/331352c1258e3c31b55e274acbb93afb5d95e54c
- [X] [`API.remove_list_members`](https://tweepy.readthedocs.io/en/latest/api.html#API.remove_list_members): https://github.com/tweepy/tweepy/commit/c8a6b67b3288869b8972622fb1f12c0a72d350b4
